[tool.commitizen]
bump_message = "chore: Release $new_version"
tag_format = "$version"
version = "1.5.1rc1"
version_files = [
    "pyproject.toml:version",
    "prompts_mcp/__init__.py:__version__"
]
changelog_incremental = true
changelog_merge_prerelease = true
update_changelog_on_bump = true
