[tool.commitizen]
bump_message = "chore: Release $new_version"
tag_format = "$version"
version = "1.4.0rc1"
version_files = [
    "pyproject.toml:version",
    "prompts_mcp/__init__.py:__version__"
]
