# Install the hooks in this file:
#   pre-commit install --hook-type pre-commit --hook-type commit-msg
#
# (optional) test hooks for staged files:
#   pre-commit run --verbose
#
# (optional) test hooks for all files:
#   pre-commit run --all-files --verbose

default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # check for basic syntax errors in python and data files
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      # check for bad files and folders
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      # best practices enforcement
      - id: detect-private-key
      - id: check-docstring-first
      - id: debug-statements
      - id: forbid-submodules
      - id: check-added-large-files
        args: ["--maxkb=600"]
      - id: name-tests-test
        args: ["--pytest-test-first"]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.4.0
    hooks:
      - id: editorconfig-checker
        alias: ec

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["--severity-level=medium", "--quiet"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
