# Install the hooks in this file:
#   pre-commit install --hook-type pre-commit --hook-type commit-msg
#
# (optional) test hooks for staged files:
#   pre-commit run --verbose
#
# (optional) test hooks for all files:
#   pre-commit run --all-files --verbose

default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.4.0
    hooks:
      - id: editorconfig-checker
        alias: ec

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
