[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "prompts-mcp"
version = "0.1.0"
description = "MCP server that serves prompts from local directory"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.14.1",
]

[project.scripts]
prompts-mcp = "prompts_mcp.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["prompts_mcp*"]
exclude = ["prompts"]
