[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "prompts-mcp"
version = "1.0.6"
description = "MCP server that serves prompts from local directory"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.14.1",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0",
    "pytest-cov>=4.0.0",
]

[project.scripts]
prompts-mcp = "prompts_mcp.main:main"
