name: Build package

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions: read-all

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            UV_NO_CONFIG: 1
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13"]

        steps:
            - uses: actions/checkout@v5

            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                  version: "latest"

            - name: Install Python ${{ matrix.python-version }}
              run: |
                  uv python install ${{ matrix.python-version }}

            - name: Build distributions
              run: |
                  uv build
