name: Setup development

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  development:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install .python-version
        run: |
          uv python install
          uv python update-shell

      - name: Start server (macOS & Linux)
        if: runner.os != 'Windows'
        run: |
          echo "Current directory: $(pwd)"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          export PROMPTS_DIR="$(pwd)/tests/test_prompts"
          echo "PROMPTS_DIR: $PROMPTS_DIR"
          ls -la tests/test_prompts || echo "Directory not found"
          uv run prompts-mcp > server.log 2>&1 &
          SERVER_PID=$!
          sleep 3
          kill $SERVER_PID 2>/dev/null || true
          grep -q "INFO:prompts-mcp:Starting prompts-mcp server with FastMCP" server.log && \
          grep -q "INFO:prompts-mcp:Using prompts directory:" server.log && \
          grep -q "INFO:prompts-mcp:Loaded.*prompts from" server.log

      - name: Start server (Windows)
        if: runner.os == 'Windows'
        run: |
          Write-Host "Current directory: $(Get-Location)"
          Write-Host "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          $PROMPTS_DIR = "$(Get-Location)\tests\test_prompts"
          Write-Host "PROMPTS_DIR: $PROMPTS_DIR"
          Get-ChildItem tests\test_prompts -ErrorAction SilentlyContinue | Write-Host
          $env:PROMPTS_DIR = $PROMPTS_DIR
          Start-Job -ScriptBlock { uv run prompts-mcp > server.log 2>&1 }
          Start-Sleep -Seconds 3
          Stop-Job *
          Remove-Job *
          Select-String -Path server.log -Pattern "INFO:prompts-mcp:Starting prompts-mcp server with FastMCP" -Quiet
          Select-String -Path server.log -Pattern "INFO:prompts-mcp:Using prompts directory:" -Quiet
          Select-String -Path server.log -Pattern "INFO:prompts-mcp:Loaded.*prompts from" -Quiet

      - name: Run dev.py
        run: |
          uv run dev.py all
