name: Setup development

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  devpy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Install uv (macOS & Linux)
        if: runner.os != 'Windows'
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install uv (Windows)
        if: runner.os == 'Windows'
        run: |
          powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

      - name: Install .python-version
        run: |
          uv python install

      - name: Run dev.py
        run: uv run dev.py all
        env:
          PYTHONIOENCODING: utf-8

      - name: Start server (macOS & Linux)
        if: runner.os != 'Windows'
        run: |
          export PROMPTS_DIR="$(pwd)/tests/test_prompts"

          # Create empty log file first
          touch server.log

          # Start server in background and append to log file
          uv run prompts-mcp >> server.log 2>&1 &
          SERVER_PID=$!

          # Wait up to 5 seconds for all required log messages
          timeout=5
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if grep -q "INFO:prompts-mcp:Starting prompts-mcp server with FastMCP" server.log && \
                grep -q "INFO:prompts-mcp:Using prompts directory:" server.log && \
                grep -q "INFO:prompts-mcp:Loaded.*prompts from" server.log; then
              echo "All required log messages found, stopping server"
              kill $SERVER_PID 2>/dev/null || true
              exit 0
            fi
            sleep 1
            elapsed=$((elapsed + 1))
          done

          echo "Timeout reached - required log messages not found within 5 seconds"
          echo "Server log contents:"
          cat server.log
          kill $SERVER_PID 2>/dev/null || true
          exit 1

      - name: Start server (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $env:PROMPTS_DIR = "$(Get-Location)\tests\test_prompts"

          # Create empty log file first
          New-Item -ItemType File -Path "server.log" -Force | Out-Null

          # Start server in background and redirect output to log file
          $job = Start-Job -ScriptBlock {
            Set-Location $using:PWD
            $env:PROMPTS_DIR = $using:env:PROMPTS_DIR
            uv run prompts-mcp 2>&1 | Out-File -FilePath "server.log" -Append
          }

          # Wait up to 5 seconds for all required log messages
          $timeout = 5
          $elapsed = 0
          $found = $false

          while ($elapsed -lt $timeout) {
            if (Test-Path "server.log") {
              $logContent = Get-Content "server.log" -Raw -ErrorAction SilentlyContinue
              if ($logContent -and
                  $logContent -match "INFO:prompts-mcp:Starting prompts-mcp server with FastMCP" -and
                  $logContent -match "INFO:prompts-mcp:Using prompts directory:" -and
                  $logContent -match "INFO:prompts-mcp:Loaded.*prompts from") {
                Write-Host "All required log messages found, stopping server"
                Stop-Job $job -ErrorAction SilentlyContinue
                Remove-Job $job -ErrorAction SilentlyContinue
                $found = $true
                break
              }
            }
            Start-Sleep -Seconds 1
            $elapsed++
          }

          if (-not $found) {
            Write-Host "Timeout reached - required log messages not found within 5 seconds"
            Write-Host "Server log contents:"
            if (Test-Path "server.log") {
              Get-Content "server.log"
            } else {
              Write-Host "No server.log file found"
            }
            Stop-Job $job -ErrorAction SilentlyContinue
            Remove-Job $job -ErrorAction SilentlyContinue
            exit 1
          }

      - name: Run pre-commit hooks
        run: |
          uv run pre-commit run --all-files --verbose
