name: Development

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install .python-version
        run: |
          uv python install

      - name: Run dev.py
        run: |
          ./dev.py all

      - name: Start server
        run: |
          uv run prompts-mcp > server.log 2>&1 &
          SERVER_PID=$!
          sleep 3
          kill $SERVER_PID 2>/dev/null || true
          grep -q "INFO:prompts-mcp:Starting prompts-mcp server with FastMCP" server.log && \
          grep -q "INFO:prompts-mcp:Using prompts directory:" server.log && \
          grep -q "INFO:prompts-mcp:Loaded.*prompts from" server.log
        env:
          PROMPTS_DIR: "tests/test_prompts"
