name: Setup development

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  development:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install .python-version
        run: |
          uv python install
          uv python update-shell

      - name: Start server (macOS & Linux)
        if: runner.os != 'Windows'
        run: |
          export PROMPTS_DIR="$GITHUB_WORKSPACE/tests/test_prompts"
          uv run prompts-mcp > server.log 2>&1 &
          SERVER_PID=$!
          sleep 3
          kill $SERVER_PID 2>/dev/null || true
          grep -q "INFO:prompts-mcp:Starting prompts-mcp server with FastMCP" server.log && \
          grep -q "INFO:prompts-mcp:Using prompts directory:" server.log && \
          grep -q "INFO:prompts-mcp:Loaded.*prompts from" server.log

      - name: Start server (Windows)
        if: runner.os == 'Windows'
        run: |
          set PROMPTS_DIR=%GITHUB_WORKSPACE%\tests\test_prompts
          Start-Job -ScriptBlock { uv run prompts-mcp > server.log 2>&1 }
          Start-Sleep -Seconds 3
          Stop-Job *
          Remove-Job *
          Select-String -Path server.log -Pattern "INFO:prompts-mcp:Starting prompts-mcp server with FastMCP" -Quiet
          Select-String -Path server.log -Pattern "INFO:prompts-mcp:Using prompts directory:" -Quiet
          Select-String -Path server.log -Pattern "INFO:prompts-mcp:Loaded.*prompts from" -Quiet

      - name: Run dev.py
        run: |
          uv run dev.py all
