name: Scan security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for uploading SARIF results
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install .python-version
        run: |
          uv python install

      - name: Run Bandit
        run: |
          uvx "bandit[sarif]" -r . \
            --format sarif --output bandit.sarif \
            --severity-level medium

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: github.event_name != 'act_test' && !contains(github.actor, 'act')
        with:
          sarif_file: bandit.sarif
          category: bandit

  checkov:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install .python-version
        run: |
          uv python install

      - name: Run Checkov
        run: |
          uvx checkov -d . --quiet \
            --output cli --output sarif --output-file-path console,checkov.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: github.event_name != 'act_test' && !contains(github.actor, 'act')
        with:
          sarif_file: checkov.sarif
          category: checkov
