name: Scan security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Bandit
        uses: PyCQA/bandit-action@v1
        with:
          severity: medium

  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          quiet: true
          output_format: cli
