name: Check security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          quiet: true
